"use client";

import { useState } from "react";
import Link from "next/link";
import { FlagIcon, CountryCode } from "@/components/ui/flag-icon";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  ShoppingBag,
  Search,
  Truck,
  FileText,
  CheckCircle2,
  Clock,
  MapPin,
  X,
  Printer,
  ArrowRight,
  ShieldCheck,
  Eye,
  Calendar,
} from "lucide-react";

interface LPOItem {
  poNumber: string;
  rfqRef: string;
  reqNumber: string;
  entity: string;
  flag: CountryCode | string;
  issueDate: string;
  deliveryDeadline: string;
  destination: string;
  totalValue: string;
  currency: string;
  deliveryCreated: boolean;
  deliveryNoteRef?: string;
  status: "pending_delivery" | "in_transit" | "grn_received";
  items: { description: string; qty: string; unitPrice: string; total: string }[];
}

const mockSupplierLPOs: LPOItem[] = [
  {
    poNumber: "LPO-2026-9842",
    rfqRef: "RFQ-2026-0810",
    reqNumber: "REQ-2026-4891",
    entity: "Crown Paints Kenya PLC",
    flag: "KE",
    issueDate: "Feb 27, 2026",
    deliveryDeadline: "March 5, 2026",
    destination: "Likoni Road Factory, Goods Inwards Bay 3, Industrial Area, Nairobi",
    totalValue: "KES 4,800,000",
    currency: "KES",
    deliveryCreated: false,
    status: "pending_delivery",
    items: [
      { description: "Pure Acrylic Polymer Emulsion (High Gloss Formulation)", qty: "20 MT", unitPrice: "KES 140,000 / MT", total: "KES 2,800,000" },
      { description: "Rutile Titanium Dioxide Pigment (Paint Grade 99.5%)", qty: "10 MT", unitPrice: "KES 200,000 / MT", total: "KES 2,000,000" },
    ],
  },
  {
    poNumber: "LPO-2026-9710",
    rfqRef: "RFQ-2026-0792",
    reqNumber: "REQ-2026-4720",
    entity: "Regal Paints Uganda Ltd",
    flag: "UG",
    issueDate: "Feb 23, 2026",
    deliveryDeadline: "Feb 28, 2026",
    destination: "Plot 67/69, 6th Street Industrial Area, Kampala, Uganda",
    totalValue: "UGX 64,000,000",
    currency: "UGX",
    deliveryCreated: true,
    deliveryNoteRef: "DN-UG-2026-0412",
    status: "grn_received",
    items: [
      { description: "20L Metal Paint Containers with Crown Litho Print & Handles", qty: "5,000 Units", unitPrice: "UGX 8,000", total: "UGX 40,000,000" },
      { description: "4L Plastic Paint Buckets with Airtight Security Lids", qty: "8,000 Units", unitPrice: "UGX 3,000", total: "UGX 24,000,000" },
    ],
  },
  {
    poNumber: "LPO-2026-9655",
    rfqRef: "RFQ-2026-0740",
    reqNumber: "REQ-2026-4510",
    entity: "Chromex Colourant Limited",
    flag: "CHROMEX",
    issueDate: "Feb 17, 2026",
    deliveryDeadline: "Feb 22, 2026",
    destination: "Chromex Plant, Commercial St, Industrial Area, Nairobi",
    totalValue: "KES 2,150,000",
    currency: "KES",
    deliveryCreated: true,
    deliveryNoteRef: "DN-CHR-2026-0188",
    status: "grn_received",
    items: [
      { description: "Universal Tinting Paste Dispersing Surfactants", qty: "15 Drums", unitPrice: "KES 110,000", total: "KES 1,650,000" },
      { description: "Anti-Settling Synthetic Rheology Modifiers", qty: "500 Kg", unitPrice: "KES 1,000", total: "KES 500,000" },
    ],
  },
];

export default function LPOsPage() {
  const [lpos, setLpos] = useState<LPOItem[]>(mockSupplierLPOs);
  const [searchQuery, setSearchQuery] = useState("");

  const filteredLPOs = lpos.filter((order) => {
    const q = searchQuery.toLowerCase();
    return (
      !q ||
      order.poNumber.toLowerCase().includes(q) ||
      order.rfqRef.toLowerCase().includes(q) ||
      order.entity.toLowerCase().includes(q)
    );
  });

  return (
    <div className="space-y-3.5" suppressHydrationWarning>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
        <div>
          <h1 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight">
            LPOs (Local Purchase Orders)
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Official Local Purchase Orders approved and generated by Crown Paints requisitioners for your vendor profile.
          </p>
        </div>

        <Link href="/delivery-notes">
          <Button
            suppressHydrationWarning
            className="bg-[#32298A] hover:bg-[#271f6f] text-white font-medium text-xs h-8 px-3 gap-1.5 rounded-lg cursor-pointer"
          >
            <Truck className="w-3.5 h-3.5" />
            <span>Go to Delivery Notes</span>
          </Button>
        </Link>
      </div>

      {/* Filter & Search */}
      <div className="bg-white p-2.5 sm:p-3 rounded-xl border border-slate-200/80 shadow-2xs flex flex-col sm:flex-row items-center justify-between gap-2.5">
        <div className="text-xs font-medium text-slate-500">
          Showing <strong>{filteredLPOs.length}</strong> Active Local Purchase Orders
        </div>

        <div className="relative w-full sm:w-72">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
          <Input
            placeholder="Search LPO number, RFQ Ref, or Hub…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            suppressHydrationWarning
            className="pl-8 h-8 text-xs bg-slate-50/50 border-slate-200 rounded-lg"
          />
        </div>
      </div>

      {/* LPO List Cards (Compact High-Density) */}
      <div className="space-y-3">
        {filteredLPOs.map((order) => (
          <div
            key={order.poNumber}
            className="bg-white rounded-xl border border-slate-200/80 p-3.5 sm:p-4 shadow-2xs space-y-2.5"
          >
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2 pb-2.5 border-b border-slate-100">
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-1.5">
                  <span className="text-xs font-mono font-bold text-slate-900 bg-slate-100 border border-slate-200/80 px-2 py-0.5 rounded">
                    {order.poNumber}
                  </span>
                  <span className="text-[11px] font-mono text-slate-500 bg-slate-50 border border-slate-200/60 px-1.5 py-0.5 rounded">
                    RFQ Ref: {order.rfqRef}
                  </span>
                  <div className="flex items-center gap-1.5 text-xs text-slate-600 font-medium">
                    <FlagIcon country={order.flag} className="w-3.5 h-2.5 rounded-[1px]" />
                    <span>{order.entity}</span>
                  </div>
                </div>
                <div className="flex items-center gap-1 text-[11px] text-slate-400 pt-0.5">
                  <MapPin className="w-3 h-3 text-slate-400 flex-shrink-0" />
                  <span className="truncate">{order.destination}</span>
                </div>
              </div>

              {/* Status */}
              <div className="flex-shrink-0">
                {!order.deliveryCreated ? (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-amber-50 border border-amber-200/80 text-amber-900 font-semibold text-[11px]">
                    <Clock className="w-3 h-3 text-amber-600" />
                    <span>Awaiting Dispatch</span>
                  </span>
                ) : order.status === "grn_received" ? (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-emerald-50 border border-emerald-200/80 text-emerald-800 font-semibold text-[11px]">
                    <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                    <span>GRN Received ({order.deliveryNoteRef})</span>
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-slate-100 border border-slate-200 text-slate-700 font-semibold text-xs">
                    <Truck className="w-3.5 h-3.5 text-slate-500" />
                    <span>Delivery In Transit</span>
                  </span>
                )}
              </div>
            </div>

            {/* Items Table */}
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs sm:text-sm border-collapse">
                <thead>
                  <tr className="text-slate-500 font-bold text-xs uppercase border-b border-slate-100">
                    <th className="py-2">Item Description</th>
                    <th className="py-2">Ordered Quantity</th>
                    <th className="py-2">Contract Unit Rate</th>
                    <th className="py-2 text-right">Subtotal</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {order.items.map((item, idx) => (
                    <tr key={idx} className="text-slate-700">
                      <td className="py-2 pr-2 font-medium text-slate-900">{item.description}</td>
                      <td className="py-2 font-semibold text-slate-900">{item.qty}</td>
                      <td className="py-2 text-slate-500 font-mono text-xs">{item.unitPrice}</td>
                      <td className="py-2 font-semibold text-slate-900 text-right font-mono">{item.total}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Footer Summary */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 pt-2 border-t border-slate-100 text-xs">
              <div className="flex flex-wrap items-center gap-2.5 text-xs text-slate-500">
                <span>Issued: <strong>{order.issueDate}</strong></span>
                <span>·</span>
                <span>Deadline: <strong className="text-slate-800">{order.deliveryDeadline}</strong></span>
                <span>·</span>
                <span>Total Value: <strong className="text-slate-900 font-bold font-mono">{order.totalValue}</strong></span>
              </div>

              <div className="flex items-center gap-1.5 flex-shrink-0">
                <Link href={`/lpos/${order.poNumber}`}>
                  <Button
                    variant="outline"
                    size="sm"
                    suppressHydrationWarning
                    className="h-8 px-3 text-xs font-medium border-slate-200 hover:bg-slate-50 text-slate-700 rounded-lg cursor-pointer gap-1"
                  >
                    <Eye className="w-3.5 h-3.5 text-slate-400" />
                    <span>View LPO PDF</span>
                  </Button>
                </Link>

                {!order.deliveryCreated ? (
                  <Link href={`/delivery-notes?po=${order.poNumber}`}>
                    <Button
                      size="sm"
                      suppressHydrationWarning
                      className="h-7.5 px-3 text-xs font-semibold bg-[#32298A] hover:bg-[#271f6f] text-white gap-1 rounded-lg cursor-pointer shadow-2xs"
                    >
                      <Truck className="w-3 h-3" />
                      <span>Create Delivery</span>
                    </Button>
                  </Link>
                ) : (
                  <Link href="/delivery-notes">
                    <Button
                      variant="outline"
                      size="sm"
                      suppressHydrationWarning
                      className="h-7.5 px-2.5 text-xs font-medium text-slate-500 border-slate-200 rounded-lg"
                    >
                      <span>Delivery Created</span>
                    </Button>
                  </Link>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
